### ISSUE TITLE
Crashes when teams > 2 and courts < teams / 2

### ISSUE THREAD

**Issue by lyze237** [boldcompass/roundrobinscheduler#1]
Hello!

There's a limiation to your schedule software.

It sadly crashes when it tries to render the schedule when I set as parameters something like:

* 10 teams, 4 courts
* 8 teams, 3 courts
* And so on!

It would be really awesome if the program could handle those scenarios as well (with adding breaks for teams)!

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SomeTechie.RoundRobinScheduler.ScheduleDisplay.courtRoundsPanel_Paint(Object sender, PaintEventArgs e)
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
RoundRobinScheduler
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Users/wml/AppData/Local/Apps/2.0/30AHLHK4.D28/37Y9H7LN.Z65/roun..tion_89d7ea1a7f1d5e6a_0001.0001_ec729156cba93a03/RoundRobinScheduler.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Round Robin Schedule Generator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/wml/AppData/Local/Apps/2.0/30AHLHK4.D28/37Y9H7LN.Z65/roun..tion_89d7ea1a7f1d5e6a_0001.0001_ec729156cba93a03/Round%20Robin%20Schedule%20Generator.DLL
----------------------------------------
System.Web.Extensions
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8833
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Extensions/3.5.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8825 (WinRelRS3.050727-8800)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8833 built by: WinRelRS3
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by joshuadwire** [comment]
Thanks for reporting this. The error should now be fixed in 63d14b3bd21eca45bae304ef4ab86cd1b42846c7, and if you installed using the setup.exe, you should get the update automatically by relaunching the program. 

The divider lines on the schedule page won't display correctly (that's what was causing the error), but you at least shouldn't get the error. I'm not actively working on this project anymore, so I don't expect to fix the dividing line drawings or to add any more features.

Feel free to submit a pull request with changes though if you'd like.
